---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: server
    run_list:
      - mutex_identity::server
      - mutex_identity_test::server
    attributes:
      mutex_identity:
        port: 7305
