---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.7

suites:
  - name: server
    run_list:
      - lock_rdlm::server
      - lock_rdlm_test::server
      - lock_rdlm_test::function_tests
    attributes:
      lock_rdlm:
        port: 7305
    include:
      - centos-6.7
