---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.7

suites:
  - name: server
    run_list:
      - mutex_rdlm::server
      - mutex_rdlm_test::server
    attributes:
      mutex_rdlm:
        port: 7305
    include:
      - centos-6.7
