name             'mutex-identity'
maintainer       'Backslasher'
maintainer_email 'nitz.raz@gmail.com'
license          'GPL v2'
description      'Installs/Configures mutex-identity'
long_description 'Installs/Configures mutex-identity'
version          '0.1.0'
